import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'fr' | 'de' | 'ru' | 'es' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_identity: "Identity",
    nav_patents: "Patents",
    nav_cv: "CV",
    nav_library: "Library",
    nav_gallery: "Gallery",
    hero_subtitle: "Scientific Profile",
    hero_title_1: "Dr. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "International Inventor & Researcher specializing in Strategic Vigilance. Bridging the gap between academic research and global innovation.",
    hero_status_label: "Status",
    hero_status_value: "Active Researcher",
    hero_focus_label: "Focus",
    hero_focus_value: "Strategic Intelligence",
    hero_view_cv: "View Academic CV",
    patents_title: "International Patents",
    patents_subtitle: "Innovation Portfolio",
    cv_title: "Career Timeline",
    cv_subtitle: "Professional Path",
    cv_publications: "Scientific Publications",
    cv_view_full: "View Full Professional CV",
    library_title: "Research Library",
    library_subtitle: "Scientific Documentation",
    gallery_title: "Events & Discussions",
    gallery_subtitle: "Visual Journey",
    footer_rights: "All rights reserved.",
    footer_contact: "Contact",
    footer_location: "Algeria / International",
    footer_name: "Dr. Meriem Lamrous",
    patent_status_confirmed: "Confirmed by International Authorities",
    patent_confirmed_label: "Patentability Confirmed",
    patent_status_label: "Status",
    patent1_title: "Monitoring Device (Warehouse monitoring device)",
    patent1_desc: "A specialized monitoring apparatus designed for high-precision data acquisition and strategic vigilance tracking, published in November 2024.",
    patent2_title: "Bread and Bakery Products Cutting Machine",
    patent2_desc: "Innovative automated cutting system for bakery products, recognized for its novelty and industrial applicability in October 2024.",
    patent3_title: "Comprehensive Monitoring Device for Multi-Sectoral Information Systems",
    patent3_desc: "Advanced monitoring device for multi-sectoral information systems, published in September 2024 with positive evaluations in novelty and inventive activity.",
    cv_timeline_1_title: "International Patent Filing",
    cv_timeline_1_inst: "WIPO / Algerian Patent Office",
    cv_timeline_1_desc: "Successfully filed two international patents (PCT) in the field of Strategic Vigilance and Intelligence Systems.",
    cv_timeline_2_title: "Senior Researcher",
    cv_timeline_2_inst: "Strategic Intelligence Lab",
    cv_timeline_2_desc: "Leading research initiatives on digital transformation and strategic monitoring for industrial sectors.",
    cv_timeline_3_title: "PhD in Strategic Vigilance",
    cv_timeline_3_inst: "University of Science & Technology",
    cv_timeline_3_desc: "Doctoral thesis focused on the integration of artificial intelligence in strategic decision-making processes.",
    cv_pub_1: "The Impact of Strategic Vigilance on Organizational Resilience (2023)",
    cv_pub_2: "Digital Ecosystems and Competitive Intelligence: A New Paradigm (2022)",
    cv_pub_3: "Adaptive Monitoring Systems for Emerging Markets (2021)",
    cv_pub_4: "Strategic Vigilance: From Theory to International Patentability (2024)",
    cv_dossier_info: "Full academic dossier including certifications, detailed research methodologies, and international citations.",
    cv_modal_title: "Academic Curriculum Vitae",
    cv_modal_page: "Page",
    cv_modal_of: "of",
    gallery_group1_title: "Photos with the Minister of Higher Education and Scientific Research, Kamel Baddari, and the Minister of Knowledge Economy at the Artificial Intelligence Exhibition of the House of artificial intelligence.",
    gallery_group2_title: "Photos with the Minister of Knowledge Economy, Start-ups and Micro-enterprises, Yacine Oualid, at the Innovation Exhibition held at the Annaba Innovation Center in Annaba.",
    gallery_group3_title: "Photo with the Minister of Communication, Mr. Laagab.",
    gallery_group4_title: "Photos with the President and members of the African Parliament",
    gallery_group5_title: "Photos from participation in innovative project evaluation competitions; from training workshops for start-up project holders; from the Algerian–Italian Economic Forum; and from national and international lectures and conferences in the field of research and scientific theorization.",
    gallery_cap_exhibition: "Exhibition Discussion",
    gallery_cap_ministerial: "Ministerial Visit",
    gallery_cap_ai_showcase: "AI Showcase",
    gallery_cap_innovation_dialogue: "Innovation Dialogue",
    gallery_cap_innovation_showcase: "Innovation Showcase",
    gallery_cap_ministerial_meeting: "Ministerial Meeting",
    gallery_cap_annaba: "Annaba Innovation Center",
    gallery_cap_project_presentation: "Project Presentation",
    gallery_cap_exhibition_tour: "Exhibition Tour",
    gallery_cap_dialogue_startups: "Dialogue with Startups",
    gallery_cap_innovation_ecosystem: "Innovation Ecosystem",
    gallery_cap_parliamentary: "Parliamentary Session",
    gallery_cap_diplomatic: "Diplomatic Dialogue",
    gallery_cap_project_eval: "Project Evaluation",
    gallery_cap_training: "Training Workshop",
    gallery_cap_economic_forum: "Economic Forum",
    gallery_cap_scientific_conf: "Scientific Conference",
    gallery_cap_research_pres: "Research Presentation",
    gallery_cap_intl_lecture: "International Lecture",
    gallery_cap_academic_exchange: "Academic Exchange",
    gallery_cap_prof_workshop: "Professional Workshop",
    gallery_cap_scientific_theorization: "Scientific Theorization",
    library_doc1_title: "Strategic Vigilance: A New Framework",
    library_doc1_desc: "Technical documentation outlining the theoretical foundations of the patented monitoring systems.",
    library_doc2_title: "AI in Industrial Monitoring",
    library_doc2_desc: "Research paper on the integration of machine learning algorithms in strategic intelligence.",
    library_doc3_title: "Global Innovation Trends 2024",
    library_doc3_desc: "Analysis of international patent landscapes and emerging technological sectors.",
    library_view_original: "View Original",
    library_study_mode: "Study Mode",
    library_search_placeholder: "Search documents...",
    library_category_patent: "Patent Document",
    library_category_research: "Research Paper",
    library_status_label: "Status",
    library_keywords_label: "Keywords",
    library_abstract_label: "Abstract",
  },
  ar: {
    nav_identity: "الهوية",
    nav_patents: "براءات الاختراع",
    nav_cv: "السيرة الذاتية",
    nav_library: "المكتبة",
    nav_gallery: "المعرض",
    hero_subtitle: "الملف العلمي",
    hero_title_1: "مريم",
    hero_title_2: "لمروس",
    hero_desc: "مخترعة وباحثة دولية متخصصة في اليقظة الاستراتيجية. جسر التواصل بين البحث الأكاديمي والابتكار العالمي.",
    hero_status_label: "الحالة",
    hero_status_value: "باحثة نشطة",
    hero_focus_label: "التركيز",
    hero_focus_value: "الذكاء الاستراتيجي",
    hero_view_cv: "عرض السيرة الذاتية",
    patents_title: "براءات الاختراع الدولية",
    patents_subtitle: "محفظة الابتكار",
    cv_title: "المسار المهني",
    cv_subtitle: "المسار الاحترافي",
    cv_publications: "المنشورات العلمية",
    cv_view_full: "عرض السيرة الذاتية الكاملة",
    library_title: "المكتبة البحثية",
    library_subtitle: "التوثيق العلمي",
    gallery_title: "الفعاليات والنقاشات",
    gallery_subtitle: "رحلة بصرية",
    footer_rights: "جميع الحقوق محفوظة.",
    footer_contact: "اتصل بنا",
    footer_location: "الجزائر / دولي",
    footer_name: "مريم لمروس",
    patent_status_confirmed: "مؤكد من قبل السلطات الدولية",
    patent_confirmed_label: "تم تأكيد قابلية براءة الاختراع",
    patent_status_label: "الحالة",
    patent1_title: "جهاز مراقبة (جهاز مراقبة المستودعات)",
    patent1_desc: "جهاز مراقبة متخصص مصمم للحصول على بيانات عالية الدقة وتتبع اليقظة الاستراتيجية، نُشر في نوفمبر 2024.",
    patent2_title: "آلة تقطيع الخبز ومنتجات المخابز",
    patent2_desc: "نظام تقطيع آلي مبتكر لمنتجات المخابز، معترف به لجدته وقابليته للتطبيق الصناعي في أكتوبر 2024.",
    patent3_title: "جهاز مراقبة شامل لأنظمة المعلومات متعددة القطاعات",
    patent3_desc: "جهاز مراقبة متطور لأنظمة المعلومات متعددة القطاعات، نُشر في سبتمبر 2024 مع تقييمات إيجابية في الجدة والنشاط الابتكاري.",
    cv_timeline_1_title: "إيداع براءات اختراع دولية",
    cv_timeline_1_inst: "الويبو / المكتب الجزائري لبراءات الاختراع",
    cv_timeline_1_desc: "تم إيداع براءتين دوليتين (PCT) بنجاح في مجال اليقظة الاستراتيجية وأنظمة الذكاء.",
    cv_timeline_2_title: "باحثة أولى",
    cv_timeline_2_inst: "مختبر الذكاء الاستراتيجي",
    cv_timeline_2_desc: "قيادة مبادرات بحثية حول التحول الرقمي والمراقبة الاستراتيجية للقطاعات الصناعية.",
    cv_timeline_3_title: "دكتوراه في اليقظة الاستراتيجية",
    cv_timeline_3_inst: "جامعة العلوم والتكنولوجيا",
    cv_timeline_3_desc: "أطروحة دكتوراه ركزت على دمج الذكاء الاصطناعي في عمليات صنع القرار الاستراتيجي.",
    cv_pub_1: "تأثير اليقظة الاستراتيجية على المرونة التنظيمية (2023)",
    cv_pub_2: "الأنظمة البيئية الرقمية والذكاء التنافسي: نموذج جديد (2022)",
    cv_pub_3: "أنظمة المراقبة التكيفية للأسواق الناشئة (2021)",
    cv_pub_4: "اليقظة الاستراتيجية: من النظرية إلى قابلية براءة الاختراع الدولية (2024)",
    cv_dossier_info: "ملف أكاديمي كامل يتضمن الشهادات ومنهجيات البحث التفصيلية والاقتباسات الدولية.",
    cv_modal_title: "السيرة الذاتية الأكاديمية",
    cv_modal_page: "صفحة",
    cv_modal_of: "من",
    gallery_group1_title: "صور مع وزير التعليم العالي والبحث العلمي كمال بداري ووزير اقتصاد المعرفة في معرض الذكاء الاصطناعي ببيت الذكاء الاصطناعي.",
    gallery_group2_title: "صور مع وزير اقتصاد المعرفة والمؤسسات الناشئة والمؤسسات المصغرة ياسين وليد في معرض الابتكار بمركز عنابة للابتكار.",
    gallery_group3_title: "صورة مع وزير الاتصال السيد لعقاب.",
    gallery_group4_title: "صور مع رئيس وأعضاء البرلمان الأفريقي.",
    gallery_group5_title: "صور من المشاركة في مسابقات تقييم المشاريع المبتكرة؛ من ورش عمل تدريبية لأصحاب المشاريع الناشئة؛ من المنتدى الاقتصادي الجزائري الإيطالي؛ ومن محاضرات ومؤتمرات وطنية ودولية في مجال البحث والتنظير العلمي.",
    gallery_cap_exhibition: "نقاش المعرض",
    gallery_cap_ministerial: "زيارة وزارية",
    gallery_cap_ai_showcase: "عرض الذكاء الاصطناعي",
    gallery_cap_innovation_dialogue: "حوار الابتكار",
    gallery_cap_innovation_showcase: "عرض الابتكار",
    gallery_cap_ministerial_meeting: "اجتماع وزاري",
    gallery_cap_annaba: "مركز عنابة للابتكار",
    gallery_cap_project_presentation: "عرض المشروع",
    gallery_cap_exhibition_tour: "جولة في المعرض",
    gallery_cap_dialogue_startups: "حوار مع الشركات الناشئة",
    gallery_cap_innovation_ecosystem: "نظام الابتكار البيئي",
    gallery_cap_parliamentary: "جلسة برلمانية",
    gallery_cap_diplomatic: "حوار دبلوماعي",
    gallery_cap_project_eval: "تقييم المشروع",
    gallery_cap_training: "ورشة عمل تدريبية",
    gallery_cap_economic_forum: "المنتدى الاقتصادي",
    gallery_cap_scientific_conf: "مؤتمر علمي",
    gallery_cap_research_pres: "عرض بحثي",
    gallery_cap_intl_lecture: "محاضرة دولية",
    gallery_cap_academic_exchange: "تبادل أكاديمي",
    gallery_cap_prof_workshop: "ورشة عمل مهنية",
    gallery_cap_scientific_theorization: "التنظير العلمي",
    library_doc1_title: "اليقظة الاستراتيجية: إطار جديد",
    library_doc1_desc: "وثائق تقنية توضح الأسس النظرية لأنظمة المراقبة الحاصلة على براءة اختراع.",
    library_doc2_title: "الذكاء الاصطناعي في المراقبة الصناعية",
    library_doc2_desc: "ورقة بحثية حول دمج خوارزميات التعلم الآلي في الذكاء الاستراتيجي.",
    library_doc3_title: "اتجاهات الابتكار العالمي 2024",
    library_doc3_desc: "تحليل لمشاهد براءات الاختراع الدولية والقطاعات التكنولوجية الناشئة.",
    library_view_original: "عرض الأصل",
    library_study_mode: "وضع الدراسة",
    library_search_placeholder: "البحث في المستندات...",
    library_category_patent: "وثيقة براءة اختراع",
    library_category_research: "ورقة بحثية",
    library_status_label: "الحالة",
    library_keywords_label: "الكلمات المفتاحية",
    library_abstract_label: "الملخص",
  },
  fr: {
    nav_identity: "Identité",
    nav_patents: "Brevets",
    nav_cv: "CV",
    nav_library: "Bibliothèque",
    nav_gallery: "Galerie",
    hero_subtitle: "Profil Scientifique",
    hero_title_1: "Dr. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Inventrice & Chercheuse internationale spécialisée en Veille Stratégique. Faire le pont entre la recherche académique et l'innovation mondiale.",
    hero_status_label: "Statut",
    hero_status_value: "Chercheuse Active",
    hero_focus_label: "Focus",
    hero_focus_value: "Intelligence Stratégique",
    hero_view_cv: "Voir le CV Académique",
    patents_title: "Brevets Internationaux",
    patents_subtitle: "Portefeuille d'Innovation",
    cv_title: "Parcours Professionnel",
    cv_subtitle: "Cheminement",
    cv_publications: "Publications Scientifiques",
    cv_view_full: "Voir le CV Professionnel Complet",
    library_title: "Bibliothèque de Recherche",
    library_subtitle: "Documentation Scientifique",
    gallery_title: "Événements & Discussions",
    gallery_subtitle: "Voyage Visuel",
    footer_rights: "Tous droits réservés.",
    footer_contact: "Contact",
    footer_location: "Algérie / International",
    footer_name: "Dr. Meriem Lamrous",
    patent_status_confirmed: "Confirmé par les autorités internationales",
    patent_confirmed_label: "Brevetabilité confirmée",
    patent_status_label: "Statut",
    patent1_title: "Dispositif de surveillance (Dispositif de surveillance d'entrepôt)",
    patent1_desc: "Un appareil de surveillance spécialisé conçu pour l'acquisition de données de haute précision et le suivi de la veille stratégique, publié en novembre 2024.",
    patent2_title: "Machine à couper le pain et les produits de boulangerie",
    patent2_desc: "Système de coupe automatisé innovant pour les produits de boulangerie, reconnu pour sa nouveauté et son applicabilité industrielle en octobre 2024.",
    patent3_title: "Dispositif de surveillance complet pour les systèmes d'information multisectoriels",
    patent3_desc: "Dispositif de surveillance avancé pour les systèmes d'information multisectoriels, publié en septembre 2024 avec des évaluations positives en matière de nouveauté et d'activité inventive.",
    cv_timeline_1_title: "Dépôt de brevet international",
    cv_timeline_1_inst: "OMPI / Office algérien des brevets",
    cv_timeline_1_desc: "Dépôt réussi de deux brevets internationaux (PCT) dans le domaine de la veille stratégique et des systèmes d'intelligence.",
    cv_timeline_2_title: "Chercheuse principale",
    cv_timeline_2_inst: "Laboratoire d'intelligence stratégique",
    cv_timeline_2_desc: "Direction d'initiatives de recherche sur la transformation numérique et le suivi stratégique pour les secteurs industriels.",
    cv_timeline_3_title: "Doctorat en Veille Stratégique",
    cv_timeline_3_inst: "Université des Sciences et de la Technologie",
    cv_timeline_3_desc: "Thèse de doctorat portant sur l'intégration de l'intelligence artificielle dans les processus de prise de décision stratégique.",
    cv_pub_1: "L'impact de la veille stratégique sur la résilience organisationnelle (2023)",
    cv_pub_2: "Écosystèmes numériques et intelligence compétitive : Un nouveau paradigme (2022)",
    cv_pub_3: "Systèmes de surveillance adaptatifs pour les marchés émergents (2021)",
    cv_pub_4: "Veille stratégique : De la théorie à la brevetabilité internationale (2024)",
    cv_dossier_info: "Dossier académique complet comprenant les certifications, les méthodologies de recherche détaillées et les citations internationales.",
    cv_modal_title: "Curriculum Vitae Académique",
    cv_modal_page: "Page",
    cv_modal_of: "sur",
    gallery_cap_scientific_theorization: "Théorisation scientifique",
    library_doc1_title: "Vigilance stratégique : Un nouveau cadre",
    library_doc1_desc: "Documentation technique décrivant les fondements théoriques des systèmes de surveillance brevetés.",
    library_doc2_title: "L'IA dans la surveillance industrielle",
    library_doc2_desc: "Article de recherche sur l'intégration des algorithmes d'apprentissage automatique dans l'intelligence stratégique.",
    library_doc3_title: "Tendances mondiales de l'innovation 2024",
    library_doc3_desc: "Analyse des paysages internationaux des brevets et des secteurs technologiques émergents.",
    library_view_original: "Voir l'original",
    library_study_mode: "Mode d'étude",
    library_search_placeholder: "Rechercher des documents...",
    library_category_patent: "Document de brevet",
    library_category_research: "Article de recherche",
    library_status_label: "Statut",
    library_keywords_label: "Mots-clés",
    library_abstract_label: "Résumé",
  },
  de: {
    nav_identity: "Identität",
    nav_patents: "Patente",
    nav_cv: "Lebenslauf",
    nav_library: "Bibliothek",
    nav_gallery: "Galerie",
    hero_subtitle: "Wissenschaftliches Profil",
    hero_title_1: "Dr. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Internationale Erfinderin & Forscherin, spezialisiert auf strategische Wachsamkeit. Überbrückung der Lücke zwischen akademischer Forschung und globaler Innovation.",
    hero_status_label: "Status",
    hero_status_value: "Aktive Forscherin",
    hero_focus_label: "Fokus",
    hero_focus_value: "Strategische Intelligenz",
    hero_view_cv: "Akademischen Lebenslauf ansehen",
    patents_title: "Internationale Patente",
    patents_subtitle: "Innovationsportfolio",
    cv_title: "Beruflicher Werdegang",
    cv_subtitle: "Berufsweg",
    cv_publications: "Wissenschaftliche Publikationen",
    cv_view_full: "Vollständigen Lebenslauf ansehen",
    library_title: "Forschungsbibliothek",
    library_subtitle: "Wissenschaftliche Dokumentation",
    gallery_title: "Veranstaltungen & Diskussionen",
    gallery_subtitle: "Visuelle Reise",
    footer_rights: "Alle Rechte vorbehalten.",
    footer_contact: "Kontakt",
    footer_location: "Algerien / International",
    footer_name: "Dr. Meriem Lamrous",
    gallery_cap_scientific_theorization: "Wissenschaftliche Theoretisierung",
    library_doc1_title: "Strategische Wachsamkeit: Ein neuer Rahmen",
    library_doc1_desc: "Technische Dokumentation der theoretischen Grundlagen der patentierten Überwachungssysteme.",
    library_doc2_title: "KI in der industriellen Überwachung",
    library_doc2_desc: "Forschungsarbeit über die Integration von Algorithmen für maschinelles Lernen in die strategische Intelligenz.",
    library_doc3_title: "Globale Innovationstrends 2024",
    library_doc3_desc: "Analyse der internationalen Patentlandschaften und aufstrebender Technologiebereiche.",
    library_view_original: "Original ansehen",
    library_study_mode: "Studienmodus",
    library_search_placeholder: "Dokumente suchen...",
    library_category_patent: "Patentdokument",
    library_category_research: "Forschungsarbeit",
    library_status_label: "Status",
    library_keywords_label: "Schlüsselwörter",
    library_abstract_label: "Zusammenfassung",
  },
  es: {
    nav_identity: "Identidad",
    nav_patents: "Patentes",
    nav_cv: "CV",
    nav_library: "Biblioteca",
    nav_gallery: "Galería",
    hero_subtitle: "Perfil Científico",
    hero_title_1: "Dra. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Inventora e investigadora internacional especializada en Vigilancia Estratégica. Cerrando la brecha entre la investigación académica y la innovación global.",
    hero_status_label: "Estado",
    hero_status_value: "Investigadora Activa",
    hero_focus_label: "Enfoque",
    hero_focus_value: "Inteligencia Estratégica",
    hero_view_cv: "Ver CV Académico",
    patents_title: "Patentes Internacionales",
    patents_subtitle: "Portafolio de Innovación",
    cv_title: "Trayectoria Profesional",
    cv_subtitle: "Camino Profesional",
    cv_publications: "Publicaciones Científicas",
    cv_view_full: "Ver CV Profesional Completo",
    library_title: "Biblioteca de Investigación",
    library_subtitle: "Documentación Científica",
    gallery_title: "Eventos y Discusiones",
    gallery_subtitle: "Viaje Visual",
    footer_rights: "Todos los derechos reservados.",
    footer_contact: "Contacto",
    footer_location: "Argelia / Internacional",
    footer_name: "Dra. Meriem Lamrous",
    gallery_cap_scientific_theorization: "Teorización científica",
    library_doc1_title: "Vigilancia Estratégica: Un Nuevo Marco",
    library_doc1_desc: "Documentación técnica que describe los fundamentos teóricos de los sistemas de monitoreo patentados.",
    library_doc2_title: "IA en el Monitoreo Industrial",
    library_doc2_desc: "Documento de investigación sobre la integración de algoritmos de aprendizaje automático en la inteligencia estratégica.",
    library_doc3_title: "Tendencias Globales de Innovación 2024",
    library_doc3_desc: "Análisis de los panoramas internacionales de patentes y sectores tecnológicos emergentes.",
    library_view_original: "Ver Original",
    library_study_mode: "Modo de Estudio",
    library_search_placeholder: "Buscar documentos...",
    library_category_patent: "Documento de Patente",
    library_category_research: "Documento de Investigación",
    library_status_label: "Estado",
    library_keywords_label: "Palabras clave",
    library_abstract_label: "Resumen",
  },
  pt: {
    nav_identity: "Identidade",
    nav_patents: "Patentes",
    nav_cv: "CV",
    nav_library: "Biblioteca",
    nav_gallery: "Galeria",
    hero_subtitle: "Perfil Científico",
    hero_title_1: "Dra. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Inventora e pesquisadora internacional especializada em Vigilância Estratégica. Unindo a lacuna entre a pesquisa acadêmica e a inovação global.",
    hero_status_label: "Status",
    hero_status_value: "Pesquisadora Ativa",
    hero_focus_label: "Foco",
    hero_focus_value: "Inteligência Estratégica",
    hero_view_cv: "Ver CV Acadêmico",
    patents_title: "Patentes Internacionais",
    patents_subtitle: "Portfólio de Inovação",
    cv_title: "Trajetória Profissional",
    cv_subtitle: "Caminho Profissional",
    cv_publications: "Publicações Científicas",
    cv_view_full: "Ver CV Profissional Completo",
    library_title: "Biblioteca de Pesquisa",
    library_subtitle: "Documentação Científica",
    gallery_title: "Eventos e Discussões",
    gallery_subtitle: "Jornada Visual",
    footer_rights: "Todos os direitos reservados.",
    footer_contact: "Contato",
    footer_location: "Argélia / Internacional",
    footer_name: "Dra. Meriem Lamrous",
    gallery_cap_scientific_theorization: "Teorização Científica",
    library_doc1_title: "Vigilância Estratégica: Uma Nova Estrutura",
    library_doc1_desc: "Documentação técnica descrevendo os fundamentos teóricos dos sistemas de monitoramento patenteados.",
    library_doc2_title: "IA no Monitoramento Industrial",
    library_doc2_desc: "Artigo de pesquisa sobre a integração de algoritmos de aprendizado de máquina na inteligência estratégica.",
    library_doc3_title: "Tendências Globais de Inovação 2024",
    library_doc3_desc: "Análise de cenários internacionais de patentes e setores tecnológicos emergentes.",
    library_view_original: "Ver Original",
    library_study_mode: "Modo de Estudo",
    library_search_placeholder: "Pesquisar documentos...",
    library_category_patent: "Documento de Patente",
    library_category_research: "Artigo de Pesquisa",
    library_status_label: "Status",
    library_keywords_label: "Palavras-chave",
    library_abstract_label: "Resumo",
  },
  ru: {
    nav_identity: "Личность",
    nav_patents: "Патенты",
    nav_cv: "Резюме",
    nav_library: "Библиотека",
    nav_gallery: "Галерея",
    hero_subtitle: "Научный профиль",
    hero_title_1: "Д-р Мерием",
    hero_title_2: "Ламрус",
    hero_desc: "Международный изобретатель и исследователь, специализирующийся на стратегической бдительности. Сокращение разрыва между академическими исследованиями и глобальными инновациями.",
    hero_status_label: "Статус",
    hero_status_value: "Активный исследователь",
    hero_focus_label: "Фокус",
    hero_focus_value: "Стратегическая разведка",
    hero_view_cv: "Посмотреть академическое резюме",
    patents_title: "Международные патенты",
    patents_subtitle: "Инновационный портфель",
    cv_title: "Профессиональный путь",
    cv_subtitle: "Карьера",
    cv_publications: "Научные публикации",
    cv_view_full: "Посмотреть полное резюме",
    library_title: "Исследовательская библиотека",
    library_subtitle: "Научная документация",
    gallery_title: "События и дискуссии",
    gallery_subtitle: "Визуальное путешествие",
    footer_rights: "Все права защищены.",
    footer_contact: "Контакт",
    footer_location: "Алжир / Международный",
    footer_name: "Д-р Мерием Ламрус",
    gallery_cap_scientific_theorization: "Научная теоретизация",
    library_doc1_title: "Стратегическая бдительность: новая структура",
    library_doc1_desc: "Техническая документация, излагающая теоретические основы запатентованных систем мониторинга.",
    library_doc2_title: "ИИ в промышленном мониторинге",
    library_doc2_desc: "Исследовательская работа по интеграции алгоритмов машинного обучения в стратегическую разведку.",
    library_doc3_title: "Мировые инновационные тенденции 2024",
    library_doc3_desc: "Анализ международных патентных ландшафтов и развивающихся технологических секторов.",
    library_view_original: "Посмотреть оригинал",
    library_study_mode: "Режим обучения",
    library_search_placeholder: "Поиск документов...",
    library_category_patent: "Патентный документ",
    library_category_research: "Исследовательская работа",
    library_status_label: "Статус",
    library_keywords_label: "Ключевые слова",
    library_abstract_label: "Аннотация",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
