import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'fr' | 'de' | 'ru' | 'es' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_identity: "Identity",
    nav_cv: "CV",
    nav_gallery: "Gallery",
    hero_subtitle: "Scientific Profile",
    hero_title_1: "Dr. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "International Researcher specializing in Strategic Vigilance and Industrial Systems. Bridging the gap between academic theory and practical industrial intelligence.",
    hero_status_label: "Status",
    hero_status_value: "Active Researcher",
    hero_focus_label: "Focus",
    hero_focus_value: "Strategic Intelligence",
    hero_view_cv: "View Academic CV",
    cv_title: "Researcher Curriculum Vitae",
    cv_subtitle: "Academic & Professional Trajectory",
    cv_section_personal: "Personal Information",
    cv_section_experience: "Professional Experience",
    cv_section_education: "Academic Qualifications",
    cv_section_patents: "Patents",
    cv_section_awards: "Awards & Honors",
    cv_section_supervision: "Supervision & Mentoring",
    cv_section_publications: "Scientific Publications",
    cv_section_presentations: "Conference Presentations",
    cv_section_activities: "Scientific Activities",
    cv_section_teaching: "Education & Teaching",
    cv_view_full: "Download Full PDF CV",
    cv_publications: "Selected Articles",
    cv_modal_title: "Academic Dossier",
    cv_modal_page: "Page",
    cv_modal_of: "of",
    gallery_group1_title: "Photos with the Minister of Higher Education and Scientific Research, Kamel Baddari, and the Minister of Knowledge Economy at the Artificial Intelligence Exhibition of the House of artificial intelligence.",
    gallery_group2_title: "Photos with the Minister of Knowledge Economy, Start-ups and Micro-enterprises, Yacine Oualid, at the Innovation Exhibition held at the Annaba Innovation Center in Annaba.",
    gallery_group3_title: "Photo with the Minister of Communication, Mr. Laagab.",
    gallery_group4_title: "Photos with the President and members of the African Parliament",
    gallery_group5_title: "Photos from participation in innovative project evaluation competitions; from training workshops for start-up project holders; from the Algerian–Italian Economic Forum; and from national and international lectures and conferences in the field of research and scientific theorization.",
    gallery_cap_exhibition: "Exhibition Discussion",
    gallery_cap_ministerial: "Ministerial Visit",
    gallery_cap_ai_showcase: "AI Showcase",
    gallery_cap_innovation_dialogue: "Innovation Dialogue",
    gallery_cap_innovation_showcase: "Innovation Showcase",
    gallery_cap_ministerial_meeting: "Ministerial Meeting",
    gallery_cap_annaba: "Annaba Innovation Center",
    gallery_cap_project_presentation: "Project Presentation",
    gallery_cap_exhibition_tour: "Exhibition Tour",
    gallery_cap_dialogue_startups: "Dialogue with Startups",
    gallery_cap_innovation_ecosystem: "Innovation Ecosystem",
    gallery_cap_parliamentary: "Parliamentary Session",
    gallery_cap_diplomatic: "Diplomatic Dialogue",
    gallery_cap_project_eval: "Project Evaluation",
    gallery_cap_training: "Training Workshop",
    gallery_cap_economic_forum: "Economic Forum",
    gallery_cap_scientific_conf: "Scientific Conference",
    gallery_cap_research_pres: "Research Presentation",
    gallery_cap_intl_lecture: "International Lecture",
    gallery_cap_academic_exchange: "Academic Exchange",
    gallery_cap_prof_workshop: "Professional Workshop",
    gallery_cap_scientific_theorization: "Scientific Theorization",
  },
  ar: {
    nav_identity: "الهوية",
    nav_cv: "السيرة الذاتية",
    nav_gallery: "المعرض",
    hero_subtitle: "الملف العلمي",
    hero_title_1: "مريم",
    hero_title_2: "لمروس",
    hero_desc: "باحثة دولية متخصصة في اليقظة الاستراتيجية والأنظمة الصناعية. جسر التواصل بين البحث الأكاديمي والذكاء الميداني.",
    hero_status_label: "الحالة",
    hero_status_value: "باحثة نشطة",
    hero_focus_label: "التركيز",
    hero_focus_value: "الذكاء الاستراتيجي",
    hero_view_cv: "عرض السيرة الذاتية",
    cv_title: "السيرة الذاتية للباحث",
    cv_subtitle: "المسار الأكاديمي والمهني",
    cv_section_personal: "المعلومات الشخصية",
    cv_section_experience: "الخبرة المهنية",
    cv_section_education: "المؤهلات الأكاديمية",
    cv_section_patents: "براءات الاختراع",
    cv_section_awards: "الجوائز والتكريمات",
    cv_section_supervision: "الإشراف والتوجيه",
    cv_section_publications: "المنشورات العلمية",
    cv_section_presentations: "العروض والمؤتمرات",
    cv_section_activities: "النشاطات العلمية",
    cv_section_teaching: "التعليم والتدريس",
    cv_view_full: "تحميل السيرة الذاتية PDF",
    cv_publications: "مقالات مختارة",
    cv_modal_title: "الملف الأكاديمي",
    cv_modal_page: "صفحة",
    cv_modal_of: "من",
    gallery_group1_title: "صور مع وزير التعليم العالي والبحث العلمي كمال بداري ووزير اقتصاد المعرفة في معرض الذكاء الاصطناعي ببيت الذكاء الاصطناعي.",
    gallery_group2_title: "صور مع وزير اقتصاد المعرفة والمؤسسات الناشئة والمؤسسات المصغرة ياسين وليد في معرض الابتكار بمركز عنابة للابتكار.",
    gallery_group3_title: "صورة مع وزير الاتصال السيد لعقاب.",
    gallery_group4_title: "صور مع رئيس وأعضاء البرلمان الأفريقي.",
    gallery_group5_title: "صور من المشاركة في مسابقات تقييم المشاريع المبتكرة؛ من ورش عمل تدريبية لأصحاب المشاريع الناشئة؛ من المنتدى الاقتصادي الجزائري الإيطالي؛ ومن محاضرات ومؤتمرات وطنية ودولية في مجال البحث والتنظير العلمي.",
    gallery_cap_exhibition: "نقاش المعرض",
    gallery_cap_ministerial: "زيارة وزارية",
    gallery_cap_ai_showcase: "عرض الذكاء الاصطناعي",
    gallery_cap_innovation_dialogue: "حوار الابتكار",
    gallery_cap_innovation_showcase: "عرض الابتكار",
    gallery_cap_ministerial_meeting: "اجتماع وزاري",
    gallery_cap_annaba: "مركز عنابة للابتكار",
    gallery_cap_project_presentation: "عرض المشروع",
    gallery_cap_exhibition_tour: "جولة في المعرض",
    gallery_cap_dialogue_startups: "حوار مع الشركات الناشئة",
    gallery_cap_innovation_ecosystem: "نظام الابتكار البيئي",
    gallery_cap_parliamentary: "جلسة برلمانية",
    gallery_cap_diplomatic: "حوار دبلوماعي",
    gallery_cap_project_eval: "تقييم المشروع",
    gallery_cap_training: "ورشة عمل تدريبية",
    gallery_cap_economic_forum: "المنتدى الاقتصادي",
    gallery_cap_scientific_conf: "مؤتمر علمي",
    gallery_cap_research_pres: "عرض بحثي",
    gallery_cap_intl_lecture: "محاضرة دولية",
    gallery_cap_academic_exchange: "تبادل أكاديمي",
    gallery_cap_prof_workshop: "ورشة عمل مهنية",
    gallery_cap_scientific_theorization: "التنظير العلمي",
  },
  fr: {
    nav_identity: "Identité",
    nav_cv: "CV",
    nav_gallery: "Galerie",
    hero_subtitle: "Profil Scientifique",
    hero_title_1: "Dr. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Chercheuse internationale spécialisée en Veille Stratégique et Systèmes Industriels. Faire le pont entre la théorie académique et l'intelligence industrielle pratique.",
    hero_status_label: "Statut",
    hero_status_value: "Chercheuse Active",
    hero_focus_label: "Focus",
    hero_focus_value: "Intelligence Stratégique",
    hero_view_cv: "Voir le CV Académique",
    cv_title: "Parcours Professionnel",
    cv_subtitle: "Cheminement",
    cv_publications: "Publications Scientifiques",
    cv_view_full: "Voir le CV Académique Complet",
    cv_section_personal: "Informations Personnelles",
    cv_section_experience: "Expérience Professionnelle",
    cv_section_education: "Qualifications Académiques",
    cv_section_patents: "Brevets",
    cv_section_awards: "Prix et Distinctions",
    cv_section_supervision: "Supervision et Mentorat",
    cv_section_publications: "Publications Scientifiques",
    cv_section_presentations: "Présentations de Conférences",
    cv_section_activities: "Activités Scientifiques",
    cv_section_teaching: "Éducation et Enseignement",
    gallery_title: "Événements & Discussions",
    gallery_subtitle: "Voyage Visuel",
    footer_rights: "Tous droits réservés.",
    footer_contact: "Contact",
    footer_name: "Dr. Meriem Lamrous",
    cv_timeline_1_title: "Initiatives de Recherche Stratégique",
    cv_timeline_1_inst: "Conseil de la Recherche Scientifique",
    cv_timeline_1_desc: "Exploration et développement de cadres avancés pour la Veille Stratégique et les Systèmes d'Intelligence.",
    cv_timeline_2_title: "Chercheuse principale",
    cv_timeline_2_inst: "Laboratoire d'intelligence stratégique",
    cv_timeline_2_desc: "Direction d'initiatives de recherche sur la transformation numérique et le suivi stratégique pour les secteurs industriels.",
    cv_timeline_3_title: "Doctorat en Veille Stratégique",
    cv_timeline_3_inst: "Université des Sciences et de la Technologie",
    cv_timeline_3_desc: "Thèse de doctorat portant sur l'intégration de l'intelligence artificielle dans les processus de prise de décision stratégique.",
    cv_pub_1: "L'impact de la veille stratégique sur la résilience organisationnelle (2023)",
    cv_pub_2: "Écosystèmes numériques et intelligence compétitive : Un nouveau paradigme (2022)",
    cv_pub_3: "Systèmes de surveillance adaptatifs pour les marchés émergents (2021)",
    cv_pub_4: "Veille stratégique : Cadres théoriques et méthodologie (2024)",
    cv_dossier_info: "Dossier académique complet comprenant les certifications, les méthodologies de recherche détaillées et les citations internationales.",
    cv_modal_title: "Curriculum Vitae Académique",
    cv_modal_page: "Page",
    cv_modal_of: "sur",
    gallery_cap_scientific_theorization: "Théorisation scientifique",
  },
  de: {
    nav_identity: "Identität",
    nav_cv: "Lebenslauf",
    nav_gallery: "Galerie",
    hero_subtitle: "Wissenschaftliches Profil",
    hero_title_1: "Dr. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Internationale Forscherin, spezialisiert auf strategische Wachsamkeit und industrielle Systeme. Überbrückung der Lücke zwischen akademischer Theorie und praktischer industrieller Intelligenz.",
    hero_status_label: "Status",
    hero_status_value: "Aktive Forscherin",
    hero_focus_label: "Fokus",
    hero_focus_value: "Strategische Intelligenz",
    hero_view_cv: "Akademischen Lebenslauf ansehen",
    cv_title: "Beruflicher Werdegang",
    cv_subtitle: "Berufsweg",
    cv_publications: "Wissenschaftliche Publikationen",
    cv_view_full: "Vollständigen Lebenslauf ansehen",
    cv_section_personal: "Persönliche Informationen",
    cv_section_experience: "Berufserfahrung",
    cv_section_education: "Akademische Qualifikationen",
    cv_section_patents: "Patente",
    cv_section_awards: "Auszeichnungen & Ehrungen",
    cv_section_supervision: "Supervision & Mentoring",
    cv_section_publications: "Wissenschaftliche Publikationen",
    cv_section_presentations: "Konferenzvorträge",
    cv_section_activities: "Wissenschaftliche Aktivitäten",
    cv_section_teaching: "Bildung & Lehre",
    gallery_title: "Veranstaltungen & Diskussionen",
    gallery_subtitle: "Visuelle Reise",
    footer_rights: "Alle Rechte vorbehalten.",
    footer_contact: "Kontakt",
    footer_location: "Algerien / International",
    footer_name: "Dr. Meriem Lamrous",
    gallery_cap_scientific_theorization: "Wissenschaftliche Theoretisierung",
  },
  es: {
    nav_identity: "Identidad",
    nav_cv: "CV",
    nav_gallery: "Galería",
    hero_subtitle: "Perfil Científico",
    hero_title_1: "Dra. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Investigadora internacional especializada en Vigilancia Estratégica y Sistemas Industriales. Cerrando la brecha entre la teoría académica y la inteligencia industrial práctica.",
    hero_status_label: "Estado",
    hero_status_value: "Investigadora Activa",
    hero_focus_label: "Enfoque",
    hero_focus_value: "Inteligencia Estratégica",
    hero_view_cv: "Ver CV Académico",
    cv_title: "Trayectoria Profesional",
    cv_subtitle: "Camino Profesional",
    cv_publications: "Publicaciones Científicas",
    cv_view_full: "Ver CV Profesional Completo",
    cv_section_personal: "Información Personal",
    cv_section_experience: "Experiencia Profesional",
    cv_section_education: "Calificaciones Académicas",
    cv_section_patents: "Patentes",
    cv_section_awards: "Premios y Honores",
    cv_section_supervision: "Supervisión y Mentoría",
    cv_section_publications: "Publicaciones Científicas",
    cv_section_presentations: "Presentaciones en Conferencias",
    cv_section_activities: "Actividades Científicas",
    cv_section_teaching: "Educación y Enseñanza",
    gallery_title: "Eventos y Discusiones",
    gallery_subtitle: "Viaje Visual",
    footer_rights: "Todos los derechos reservados.",
    footer_contact: "Contacto",
    footer_location: "Argelia / Internacional",
    footer_name: "Dra. Meriem Lamrous",
    gallery_cap_scientific_theorization: "Teorización científica",
  },
  pt: {
    nav_identity: "Identidade",
    nav_cv: "CV",
    nav_gallery: "Galeria",
    hero_subtitle: "Perfil Científico",
    hero_title_1: "Dra. Meriem",
    hero_title_2: "Lamrous",
    hero_desc: "Pesquisadora internacional especializada em Vigilância Estratégica e Sistemas Industriais. Unindo a lacuna entre a teoria acadêmica e a inteligência industrial prática.",
    hero_status_label: "Status",
    hero_status_value: "Pesquisadora Ativa",
    hero_focus_label: "Foco",
    hero_focus_value: "Inteligência Estratégica",
    hero_view_cv: "Ver CV Acadêmico",
    cv_title: "Trajetória Profissional",
    cv_subtitle: "Caminho Profissional",
    cv_publications: "Publicações Científicas",
    cv_view_full: "Ver CV Profissional Completo",
    cv_section_personal: "Informações Pessoais",
    cv_section_experience: "Experiência Profissional",
    cv_section_education: "Qualificações Acadêmicas",
    cv_section_patents: "Patentes",
    cv_section_awards: "Prêmios e Honras",
    cv_section_supervision: "Supervisão e Mentoria",
    cv_section_publications: "Publicações Científicas",
    cv_section_presentations: "Apresentações em Conferências",
    cv_section_activities: "Atividades Científicas",
    cv_section_teaching: "Educação e Ensino",
    gallery_title: "Eventos e Discussões",
    gallery_subtitle: "Jornada Visual",
    footer_rights: "Todos os direitos reservados.",
    footer_contact: "Contato",
    footer_location: "Argélia / Internacional",
    footer_name: "Dra. Meriem Lamrous",
    gallery_cap_scientific_theorization: "Teorização Científica",
  },
  ru: {
    nav_identity: "Личность",
    nav_cv: "Резюме",
    nav_gallery: "Галерея",
    hero_subtitle: "Научный профиль",
    hero_title_1: "Д-р Мерием",
    hero_title_2: "Ламрус",
    hero_desc: "Международный исследователь, специализирующийся на стратегической бдительности и промышленных системах. Сокращение разрыва между академической теорией и практической промышленной разведкой.",
    hero_status_label: "Статус",
    hero_status_value: "Активный исследователь",
    hero_focus_label: "Фокус",
    hero_focus_value: "Стратегическая разведка",
    hero_view_cv: "Посмотреть академическое резюме",
    cv_title: "Профессиональный путь",
    cv_subtitle: "Карьера",
    cv_publications: "Научные публикации",
    cv_view_full: "Посмотреть полное резюме",
    cv_section_personal: "Личная информация",
    cv_section_experience: "Профессиональный опыт",
    cv_section_education: "Академическая квалификация",
    cv_section_patents: "Патенты",
    cv_section_awards: "Награды и почетные звания",
    cv_section_supervision: "Руководство и наставничество",
    cv_section_publications: "Научные публикации",
    cv_section_presentations: "Доклады на конференциях",
    cv_section_activities: "Научная деятельность",
    cv_section_teaching: "Образование и преподавательская деятельность",
    gallery_title: "События и дискуссии",
    gallery_subtitle: "Визуальное путешествие",
    footer_rights: "Все права защищены.",
    footer_contact: "Контакт",
    footer_location: "Алжир / Международный",
    footer_name: "Д-р Мерием Ламрус",
    gallery_cap_scientific_theorization: "Научная теоретизация",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
